### ISSUE TITLE
Google Apps Script library: Address unavailable

### ISSUE THREAD

**Issue by Sciere451** [zboris12/zgapdfsigner#3]
I've been using this project's Apps Script library (1T0UPf50gGp2fJ4dR1rZfEFgKYC5VpCwUVooCRNySiL7klvIUVsFBCZ9m) in an educational Google environment and it has been immensely helpful!

Since yesterday I encounter an error using the library when attempting to password protect PDF files:

*Exception: Address unavailable: https://zgayard.f5.si/zgapdfsigner.min.js
loadZga	@ assist.gs:89*

**Comment by Sciere451** [comment]
Appears to be fixed today, thanks.

**Comment by zboris12** [comment]
The server at this URL occasionally undergoes maintenance, so you may be unlucky to visit the server when it was under maintenance.
To avoid this, I have changed the url to access github directly, so please use version **6** from now on.
