### ISSUE TITLE
Add text will invalidates existing signatures

### ISSUE THREAD

**Issue by GlamBytesGeek** [zboris12/zgapdfsigner#6]
Hi @zboris12 
Thanks a lot for the library especially the incremental signing feature.
The issue I'm facing is that whenever I add text and then sign, it invalidates the existing signatures no matter i tried with DocMDP=0/2/3. 
I've tried to create agro form and fill up while signing also will invalidate the existing signatures.

Understanding the pdf modification should be avoided to ensure the signature validity. 
Do you have any idea on maintaining the validity of the signatures even with modification?
Thank you!

**Comment by zboris12** [comment]
Hello @GlamBytesGeek
As you know, even in `DocMDP=0/2/3` mode, only signing and form filling are allowed after first signing.
And any other changes will invalidate the previous signatures.
So I think the only way to add text is to add a text signature.
Unfortunately, this feature has not yet been implemented in this library.

If you really need this feature, please let me know.

**Comment by GlamBytesGeek** [comment]
Hi @zboris12 
Appreciate your response and willingness to help. I'll try to explore solutions on my own to avoid imposing on your time.
Thanks again for your support and for providing such a helpful library.

**Comment by zboris12** [comment]
Hello @GlamBytesGeek 
Finally I implemented this feature.
If you are still facing this issue, you may take a look at it.
https://github.com/zboris12/zgapdfsigner/wiki/API#signtextinfo

**Comment by GlamBytesGeek** [comment]
Hi @zboris12 
Thank you so much for the solution you provided. I appreciate your assistance and will give it a try.
Thanks again!
