### ISSUE TITLE
2.7.3: Status and validity of signed pdfs changed from valid status to UNKNOWN?

### ISSUE THREAD

**Issue by tfrancois** [zboris12/zgapdfsigner#8]
With the latest release, signing of documents return a validity status of `UNKNOWN - the author could not be verified`:

![image](https://github.com/user-attachments/assets/72d21817-d43f-4b28-985d-50ea13db7a46)

Previously, the same source code and signing certificate was signing documents and returning `VALID` status in Acrobat:

![image](https://github.com/user-attachments/assets/1e7bed96-3b0e-4f2a-a7ed-8fe0d19f0728)

Is there a way to sign PDF documents without certifying them as before with the current build?  And thank you - this library is by far the best and most feature-complete I've found among all of those available on npm.

**Comment by zboris12** [comment]
Hello @tfrancois 
Can you tell me how did you set the [SignOption](https://github.com/zboris12/zgapdfsigner/wiki/API#signoption),
and what version you were using previously?

**Comment by zboris12** [comment]
Hello @tfrancois 

I think maybe you have set the `permission` in [SignOption](https://github.com/zboris12/zgapdfsigner/wiki/API#signoption) now.
For certificate of [DocMDP](https://github.com/zboris12/zgapdfsigner/wiki/API#note), you need to trust it for `Certified documents`.
![image](https://github.com/user-attachments/assets/db5c7344-f236-48ac-9692-100bc8fb3c22)

In my acrobat reader, when I uncheck `Certified documents`, it shows the same status as yours.
And when I check  `Certified documents`, it shows valid.
![image](https://github.com/user-attachments/assets/b7d5839f-6a54-46f4-9681-bcf03278c365)

**Comment by tfrancois** [comment]
> Hello @tfrancois Can you tell me how did you set the [SignOption](https://github.com/zboris12/zgapdfsigner/wiki/API#signoption), and what version you were using previously?

I was using version ~2.5.2 previously I believe.  And the permission settings are:
`
permission: 2,
ltv: 1
`
Thanks again!

**Comment by zboris12** [comment]
Hello @tfrancois 
You can see there is a sentence in the first image you pasted.
`Only form fill-in, signing and page adding actions are allowed`
That means the `permission` was set to `2`.

And there is no such sentence in the second image you pasted.
So if you only want to simply sign the document, just leave the `permission` unset.

**Comment by tfrancois** [comment]
I have tested with your suggestion and leaving the permission unset and that worked! 

Thank you for your assistance - and I have to say it again, this library is EXCEPTIONAL.  Thank you for your hard work and your commitment to supporting it.
